rootProject.name = "tbd-libs"
include(
    "azure-token-client",
    "azure-token-client-default",
    "kafka",
    "mock-http-client",
    "minimal-sts-client",
    "minimal-soap-client",
    "naisful-app",
    "naisful-test-app",
    "postgres-testdatabaser",
    "retry",
    "rapids-and-rivers-api",
    "rapids-and-rivers-test",
    "rapids-and-rivers",
    "result-object",
    "signed-jwt",
    "spurtedu-client",
    "speed-client",
    "spenn-simulering-client",
    "jackson"
)
