[versions]
awaitility = "4.3.0"
flyway = "11.20.2"
hikariCP = "7.1.0"
jackson3 = "3.2.2"
java-jwt = "4.6.0"
kafka = "4.3.1"
kotlin = "2.4.10"
sasGradlePlugins = "20260807.0944"
kotlinx-coroutines = "1.11.0"
kotlinx-serialization-json = "1.11.0"
rapidsAndRivers = "2026071513121784113927"
ktor = "3.5.1"
logback = "1.6.0"
logstash-logback-encoder = "9.0"
micrometer = "1.17.0"
mockk = "1.14.11"
opentelemetry-instrumentation = "2.30.0"
postgresql = "42.7.13"
slf4j = "2.0.18"
smiley4-ktor-openapi-tools = "5.7.0"
smiley4-schema-kenerator = "2.7.2"
testcontainers = "2.0.5"

[libraries]
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }
flyway-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
hikariCP = { module = "com.zaxxer:HikariCP", version.ref = "hikariCP" }
jackson3-bom = { module = "tools.jackson:jackson-bom", version.ref = "jackson3" }
java-jwt = { module = "com.auth0:java-jwt", version.ref = "java-jwt" }
kafka-clients = { module = "org.apache.kafka:kafka-clients", version.ref = "kafka" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock-jvm", version.ref = "ktor" }
ktor-serialization-jackson3 = { module = "io.ktor:ktor-serialization-jackson3", version.ref = "ktor" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
ktor-server-auth-jwt = { module = "io.ktor:ktor-server-auth-jwt", version.ref = "ktor" }
ktor-server-call-id = { module = "io.ktor:ktor-server-call-id", version.ref = "ktor" }
ktor-server-call-logging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-metrics-micrometer = { module = "io.ktor:ktor-server-metrics-micrometer", version.ref = "ktor" }
ktor-server-resources = { module = "io.ktor:ktor-server-resources", version.ref = "ktor" }
ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logstash-logback-encoder = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logstash-logback-encoder" }
micrometer-core = { module = "io.micrometer:micrometer-core", version.ref = "micrometer" }
micrometer-registry-prometheus = { module = "io.micrometer:micrometer-registry-prometheus", version.ref = "micrometer" }
mock-oauth2-server = "no.nav.security:mock-oauth2-server:6.0.1"
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
opentelemetry-instrumentation-annotations = { module = "io.opentelemetry.instrumentation:opentelemetry-instrumentation-annotations", version.ref = "opentelemetry-instrumentation" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
rapids-and-rivers = {module = "com.github.navikt:rapids-and-rivers", version.ref = "rapidsAndRivers"}
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
smiley4-ktor-openapi = { module = "io.github.smiley4:ktor-openapi", version.ref = "smiley4-ktor-openapi-tools" }
smiley4-ktor-swagger-ui = { module = "io.github.smiley4:ktor-swagger-ui", version.ref = "smiley4-ktor-openapi-tools" }
smiley4-schema-kenerator-core = { module = "io.github.smiley4:schema-kenerator-core", version.ref = "smiley4-schema-kenerator" }
smiley4-schema-kenerator-reflection = { module = "io.github.smiley4:schema-kenerator-reflection", version.ref = "smiley4-schema-kenerator" }
smiley4-schema-kenerator-serialization = { module = "io.github.smiley4:schema-kenerator-serialization", version.ref = "smiley4-schema-kenerator" }
smiley4-schema-kenerator-swagger = { module = "io.github.smiley4:schema-kenerator-swagger", version.ref = "smiley4-schema-kenerator" }
testcontainers-core = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-kafka = { module = "org.testcontainers:testcontainers-kafka", version.ref = "testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql", version.ref = "testcontainers" }
wiremock = "org.wiremock:wiremock-jetty12:3.13.2"
valkey-java = "io.valkey:valkey-java:5.5.0"

[bundles]
smiley4-ktor-openapi-tools = [
    "smiley4-ktor-openapi",
    "smiley4-ktor-swagger-ui",
    "smiley4-schema-kenerator-core",
    "smiley4-schema-kenerator-reflection",
    "smiley4-schema-kenerator-serialization",
    "smiley4-schema-kenerator-swagger",
]

[plugins]
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
sas-kotlin = { id = "no.nav.helse.sas.sas-kotlin", version.ref = "sasGradlePlugins" }
sas-root = { id = "no.nav.helse.sas.sas-root", version.ref = "sasGradlePlugins" }
