name: main - Bygg, test og publiser

on:
  push:
    branches:
      - main
    paths:
      # Generelt oppsett - alt unntatt dokumentasjon / urelatert oppsett
      - '**'
      - '!**.md'
      - '!CODEOWNERS'
      - '!LICENSE'
      - '!docs/**'
      - '!.github/workflows/standard-dependabot-auto-merge.yml'
      - '!.github/workflows/standard-dependency-submission.yml'
      - '!.github/workflows/standard-pr.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  bygg-og-test:
    name: Bygg og test
    uses: navikt/helse-sas-github-workflows/.github/workflows/bygg-og-test-med-gradle.yml@2f6844aa5e6852c64522681b3edb09c99445ad59 # v1.0.1
    permissions:
      contents: read

  publiser:
    name: Publiser biblioteker
    needs: bygg-og-test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: temurin
          java-version: 25

      - uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0

      - name: Generer versjon
        id: versjon
        run: echo "versjon=$(TZ=Europe/Oslo date +%Y%m%d.%H%M)" >> "$GITHUB_OUTPUT"

      - name: gradlew publish
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew publish --build-cache -Pversion='${{ steps.versjon.outputs.versjon }}'
